-- AdsGram integration for GrowBot / STORM
-- Watch Reward block: 46262 -> +6 points, max 20 rewards per Baghdad day.
-- Native Task block: task-46724 -> +1 point each completed native task.

create table if not exists public.ad_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  telegram_id bigint not null,
  block_id text not null,
  day_key date not null default ((now() at time zone 'Asia/Baghdad')::date),
  status text not null default 'pending',
  started_at timestamptz not null default now(),
  rewarded_at timestamptz,
  reward_points integer not null default 6,
  check (status in ('pending', 'rewarded', 'expired')),
  check (reward_points > 0)
);

create index if not exists idx_ad_sessions_user_day_block
on public.ad_sessions(user_id, day_key, block_id, status);

create index if not exists idx_ad_sessions_pending_adsgram
on public.ad_sessions(telegram_id, block_id, status, started_at);

create table if not exists public.adsgram_native_rewards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  telegram_id bigint not null,
  block_id text not null,
  reward_points integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_adsgram_native_rewards_user
on public.adsgram_native_rewards(telegram_id, block_id, created_at desc);

create table if not exists public.adsgram_reward_log (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  query jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_adsgram_reward_log_telegram
on public.adsgram_reward_log(telegram_id, created_at desc);

insert into public.app_settings(key, value)
values
  ('adsgram_reward_block_id', '46262'),
  ('ads_daily_limit', '20'),
  ('ads_reward_points', '6'),
  ('adsgram_native_task_block_id', 'task-46724'),
  ('adsgram_native_task_reward_points', '1')
on conflict (key) do update set value = excluded.value;

create or replace function public.start_adsgram_watch_session(
  p_user_id uuid,
  p_telegram_id bigint,
  p_block_id text,
  p_daily_limit integer,
  p_reward_points integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_day date := ((now() at time zone 'Asia/Baghdad')::date);
  v_count integer;
  v_session public.ad_sessions%rowtype;
begin
  perform pg_advisory_xact_lock(p_telegram_id);

  select count(*) into v_count
  from public.ad_sessions
  where user_id = p_user_id
    and day_key = v_day
    and block_id = p_block_id
    and status = 'rewarded';

  if v_count >= p_daily_limit then
    raise exception 'AD_DAILY_LIMIT';
  end if;

  -- Expire stale pending rows for this user/block so a failed WebView
  -- cannot lock the next ad forever.
  update public.ad_sessions
  set status = 'expired'
  where user_id = p_user_id
    and block_id = p_block_id
    and status = 'pending'
    and started_at <= now() - interval '15 minutes';

  if exists (
    select 1
    from public.ad_sessions
    where user_id = p_user_id
      and block_id = p_block_id
      and status = 'pending'
      and started_at > now() - interval '15 minutes'
  ) then
    raise exception 'AD_SESSION_EXISTS';
  end if;

  insert into public.ad_sessions(
    user_id, telegram_id, block_id, day_key, status, reward_points
  )
  values(
    p_user_id, p_telegram_id, p_block_id, v_day, 'pending', p_reward_points
  )
  returning * into v_session;

  return jsonb_build_object(
    'id', v_session.id,
    'watched', v_count,
    'remaining', greatest(0, p_daily_limit - v_count)
  );
end;
$$;

create or replace function public.reward_adsgram_watch_session(
  p_telegram_id bigint,
  p_block_id text,
  p_daily_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_day date := ((now() at time zone 'Asia/Baghdad')::date);
  v_session public.ad_sessions%rowtype;
  v_balance bigint;
  v_count integer;
begin
  perform pg_advisory_xact_lock(p_telegram_id);

  select * into v_session
  from public.ad_sessions
  where telegram_id = p_telegram_id
    and block_id = p_block_id
    and day_key = v_day
    and status = 'pending'
    and started_at > now() - interval '15 minutes'
  order by started_at desc
  limit 1
  for update;

  if not found then
    raise exception 'NO_PENDING_AD';
  end if;

  select count(*) into v_count
  from public.ad_sessions
  where telegram_id = p_telegram_id
    and block_id = p_block_id
    and day_key = v_day
    and status = 'rewarded';

  if v_count >= p_daily_limit then
    raise exception 'AD_DAILY_LIMIT';
  end if;

  update public.ad_sessions
  set status = 'rewarded', rewarded_at = now()
  where id = v_session.id;

  select public.adjust_user_points(
    v_session.user_id,
    v_session.reward_points,
    'adsgram_reward',
    v_session.id,
    'مكافأة مشاهدة إعلان AdsGram'
  ) into v_balance;

  v_count := v_count + 1;

  return jsonb_build_object(
    'rewarded', true,
    'points', v_session.reward_points,
    'balance', v_balance,
    'watched', v_count,
    'remaining', greatest(0, p_daily_limit - v_count)
  );
end;
$$;

create or replace function public.get_adsgram_watch_status(
  p_user_id uuid,
  p_block_id text,
  p_daily_limit integer
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with day_rows as (
    select status
    from public.ad_sessions
    where user_id = p_user_id
      and block_id = p_block_id
      and day_key = ((now() at time zone 'Asia/Baghdad')::date)
  ),
  counts as (
    select
      count(*) filter (where status = 'rewarded')::integer as watched,
      exists(select 1 from day_rows where status = 'pending') as pending
    from day_rows
  )
  select jsonb_build_object(
    'watched', watched,
    'remaining', greatest(0, p_daily_limit - watched),
    'pending', pending
  )
  from counts;
$$;

create or replace function public.reward_adsgram_native_task(
  p_telegram_id bigint,
  p_block_id text,
  p_reward_points integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_reward public.adsgram_native_rewards%rowtype;
  v_balance bigint;
  v_count bigint;
begin
  select * into v_user
  from public.users
  where telegram_id = p_telegram_id
  limit 1
  for update;

  if not found then
    raise exception 'USER_NOT_FOUND';
  end if;

  insert into public.adsgram_native_rewards(
    user_id, telegram_id, block_id, reward_points
  )
  values(
    v_user.id, p_telegram_id, p_block_id, p_reward_points
  )
  returning * into v_reward;

  select public.adjust_user_points(
    v_user.id,
    p_reward_points,
    'adsgram_native_task',
    v_reward.id,
    'مكافأة AdsGram Native Task'
  ) into v_balance;

  select count(*) into v_count
  from public.adsgram_native_rewards
  where telegram_id = p_telegram_id
    and block_id = p_block_id;

  return jsonb_build_object(
    'rewarded', true,
    'points', p_reward_points,
    'balance', v_balance,
    'count', v_count
  );
end;
$$;

create or replace function public.expire_stale_adsgram_sessions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  update public.ad_sessions
  set status = 'expired'
  where status = 'pending'
    and started_at <= now() - interval '15 minutes';
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
